### ISSUE TITLE
[FEATURE]: Add new @Injectable decorator.

### ISSUE THREAD

**Issue by dannysmc95** [Symbux/Injector#1]
**Describe the solution you'd like**
A new decorator called `@Injectable` which is a class-level decorator, that will mark a class as injectable, then the developer can use the constructor to inject provided classes, this would then work better for things like unit testing, and is a common approach, in frameworks like Symfony (PHP).

Additionally due to the way the above would work, variable based injecting would be impossible, so maybe offer an optional array of strings inside of the `@Injectable` decorator that can be used to map variables or other properties to support that and to prevent it breaking existing support for the IDE type hints from VSCode, you can use `null` to define a pre-configured item ignoring it allowing you to define where things would be in the order specified.

_See code examples._

**Describe alternatives you've considered**
N/A

**Additional context**

Example of standard injection.
```typescript
import { Injectable } from '@symbux/orm';
import { MessageBroker } from './message-broker';

@Injectable()
export class ExampleController {
    public constructor(private broker: MessageBroker) {}
}
```

Example of variable injection support.
```typescript
import { Injectable } from '@symbux/orm';
import { MessageBroker } from './message-broker';
import { Logger } from './logger';

@Injectable(['settings', null, null, 'app.version'])
export class ExampleController {
    public constructor(
        private settings: {[key: string}: any},
        private broker: MessageBroker,
        private logger: Logger,
        private version: string
    } {}
}
```

**Comment by deathlynocturnal** [comment]
Project is deprecated, in favour of @sodacore/core project.
